name: Build EspTouch V1 XCFramework
on: workflow_dispatch
jobs:
  compile_ios_lib:
    runs-on: macos-latest
    steps:
      - name: 创建编译目录
        run: mkdir ios_build_temp
      - name: 进入目录，创建空Xcode项目 + Podfile
        working-directory: ios_build_temp
        run: |
          # 生成空临时项目
          xcodebuild -create-xcproject -project Temp.xcodeproj
          # 写入Podfile并指定项目
          cat > Podfile << EOF
          platform :ios, '11.0'
          project 'Temp.xcodeproj'
          target 'TempCompile' do
            pod 'EspTouch', '5.3.2'
          end
          EOF
          pod install --repo-update
      - name: 导出xcframework
        run: mkdir output && cp -r ios_build_temp/Pods/EspTouch/EspTouch.xcframework output/
      - name: 打包下载产物
        uses: actions/upload-artifact@v4
        with:
          name: EspTouch-V1-xcframework
          path: output
